package manager;


import javax.swing.JFrame;
import user.CustomerMode;
import user.addBook;
import user.checkout;
import user.login;
import user.search;
import user.viewCart;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sara
 */
public class ManagerMode extends javax.swing.JFrame {

    /**
     * Creates new form ManagerMode
     */
    public ManagerMode() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        search = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        addBook = new javax.swing.JButton();
        orderBook = new javax.swing.JButton();
        modifyBook = new javax.swing.JButton();
        Confirm_order = new javax.swing.JButton();
        Log_out = new javax.swing.JButton();
        REPORT = new javax.swing.JButton();
        as_user = new javax.swing.JButton();
        promote = new javax.swing.JButton();

        search.setBackground(new java.awt.Color(50, 50, 50));
        search.setFont(new java.awt.Font("Chilanka", 1, 18)); // NOI18N
        search.setForeground(new java.awt.Color(232, 236, 241));
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/rsz_3book(1).jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panel.setBackground(new java.awt.Color(51, 51, 51));
        panel.setToolTipText("Promote user");

        jLabel4.setFont(new java.awt.Font("Chilanka", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(232, 236, 241));
        jLabel4.setText("ManagerMode");

        addBook.setBackground(new java.awt.Color(50, 50, 50));
        addBook.setFont(new java.awt.Font("Chilanka", 1, 18)); // NOI18N
        addBook.setForeground(new java.awt.Color(232, 236, 241));
        addBook.setText("Add");
        addBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookActionPerformed(evt);
            }
        });

        orderBook.setBackground(new java.awt.Color(50, 50, 50));
        orderBook.setFont(new java.awt.Font("Chilanka", 1, 18)); // NOI18N
        orderBook.setForeground(new java.awt.Color(232, 236, 241));
        orderBook.setText("Order");
        orderBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderBookActionPerformed(evt);
            }
        });

        modifyBook.setBackground(new java.awt.Color(50, 50, 50));
        modifyBook.setFont(new java.awt.Font("Chilanka", 1, 18)); // NOI18N
        modifyBook.setForeground(new java.awt.Color(232, 236, 241));
        modifyBook.setText("Modify");
        modifyBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyBookActionPerformed(evt);
            }
        });

        Confirm_order.setBackground(new java.awt.Color(50, 50, 50));
        Confirm_order.setFont(new java.awt.Font("Century", 1, 16)); // NOI18N
        Confirm_order.setForeground(new java.awt.Color(232, 236, 241));
        Confirm_order.setText("Confirm order");
        Confirm_order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Confirm_orderActionPerformed(evt);
            }
        });

        Log_out.setBackground(new java.awt.Color(50, 50, 50));
        Log_out.setFont(new java.awt.Font("Century", 1, 16)); // NOI18N
        Log_out.setForeground(new java.awt.Color(232, 236, 241));
        Log_out.setText("Log out");
        Log_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Log_outActionPerformed(evt);
            }
        });

        REPORT.setBackground(new java.awt.Color(50, 50, 50));
        REPORT.setFont(new java.awt.Font("Century", 1, 16)); // NOI18N
        REPORT.setForeground(new java.awt.Color(232, 236, 241));
        REPORT.setText("REPORT");
        REPORT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REPORTActionPerformed(evt);
            }
        });

        as_user.setBackground(new java.awt.Color(50, 50, 50));
        as_user.setFont(new java.awt.Font("Century", 1, 16)); // NOI18N
        as_user.setForeground(new java.awt.Color(232, 236, 241));
        as_user.setText("Act As User");
        as_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as_userActionPerformed(evt);
            }
        });

        promote.setBackground(new java.awt.Color(50, 50, 50));
        promote.setFont(new java.awt.Font("Century", 1, 16)); // NOI18N
        promote.setForeground(new java.awt.Color(232, 236, 241));
        promote.setText("promote user");
        promote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promoteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(235, 235, 235))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(addBook, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(modifyBook)
                                .addGap(64, 64, 64)
                                .addComponent(orderBook))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(270, 270, 270)
                                .addComponent(Log_out)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(36, 36, 36)
                        .addComponent(REPORT)
                        .addGap(12, 12, 12))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(as_user)
                        .addGap(33, 33, 33)
                        .addComponent(promote)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Confirm_order)))
                .addGap(42, 42, 42))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(38, 38, 38)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBook)
                    .addComponent(modifyBook)
                    .addComponent(orderBook)
                    .addComponent(REPORT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(as_user, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(promote, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Confirm_order, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(Log_out, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void orderBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderBookActionPerformed
         // TODO add your handling code here:
        orderBook form = new orderBook();
        //signup form = new signup();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        form.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(false);
    }//GEN-LAST:event_orderBookActionPerformed

    private void addBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookActionPerformed
        // TODO add your handling code here:
        //open manager form
        insertBook form = new insertBook();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        form.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(false);
        
    }//GEN-LAST:event_addBookActionPerformed

    private void modifyBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyBookActionPerformed
        // TODO add your handling code here:
        modifyBook form = new modifyBook();
        //signup form = new signup();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        form.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(false);
    }//GEN-LAST:event_modifyBookActionPerformed

    private void Confirm_orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Confirm_orderActionPerformed
        // TODO add your handling code here:
        confirm_order form = new confirm_order();
        //signup form = new signup();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        form.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(false);
    }//GEN-LAST:event_Confirm_orderActionPerformed

    private void Log_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Log_outActionPerformed
        login form = new login();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        form.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(false);
    }//GEN-LAST:event_Log_outActionPerformed

    private void REPORTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REPORTActionPerformed
        // TODO add your handling code here:
        reports form = new reports();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        form.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(false);
    }//GEN-LAST:event_REPORTActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        //open manager form
        

    }//GEN-LAST:event_searchActionPerformed

    private void as_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as_userActionPerformed
        // TODO add your handling code here:
        CustomerMode form = new CustomerMode();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        form.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(false);
        

    }//GEN-LAST:event_as_userActionPerformed

    private void promoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promoteActionPerformed
        // TODO add your handling code here:
        promote_user form = new promote_user();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        form.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(false); 
    }//GEN-LAST:event_promoteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Confirm_order;
    private javax.swing.JButton Log_out;
    private javax.swing.JButton REPORT;
    private javax.swing.JButton addBook;
    private javax.swing.JButton as_user;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton modifyBook;
    private javax.swing.JButton orderBook;
    private javax.swing.JPanel panel;
    private javax.swing.JButton promote;
    private javax.swing.JButton search;
    // End of variables declaration//GEN-END:variables
}
