package manager;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import user.connection;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sara
 */
public class reports extends javax.swing.JFrame {

    /**
     * Creates new form ManagerMode
     */
    public reports() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        TotalSales = new javax.swing.JButton();
        TopBooks = new javax.swing.JButton();
        TopCustomers = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/rsz_3book(1).jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel4.setFont(new java.awt.Font("Chilanka", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(232, 236, 241));
        jLabel4.setText("REPORTS");

        TotalSales.setBackground(new java.awt.Color(50, 50, 50));
        TotalSales.setFont(new java.awt.Font("Chilanka", 1, 18)); // NOI18N
        TotalSales.setForeground(new java.awt.Color(232, 236, 241));
        TotalSales.setText("Total Sales");
        TotalSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalSalesActionPerformed(evt);
            }
        });

        TopBooks.setBackground(new java.awt.Color(50, 50, 50));
        TopBooks.setFont(new java.awt.Font("Chilanka", 1, 18)); // NOI18N
        TopBooks.setForeground(new java.awt.Color(232, 236, 241));
        TopBooks.setText("Top 10 Books");
        TopBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TopBooksActionPerformed(evt);
            }
        });

        TopCustomers.setBackground(new java.awt.Color(50, 50, 50));
        TopCustomers.setFont(new java.awt.Font("Chilanka", 1, 18)); // NOI18N
        TopCustomers.setForeground(new java.awt.Color(232, 236, 241));
        TopCustomers.setText("Top 5 Customers");
        TopCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TopCustomersActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(50, 50, 50));
        back.setFont(new java.awt.Font("Century", 0, 16)); // NOI18N
        back.setForeground(new java.awt.Color(232, 236, 241));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TotalSales)
                .addGap(56, 56, 56)
                .addComponent(TopCustomers)
                .addGap(55, 55, 55)
                .addComponent(TopBooks)
                .addGap(39, 39, 39))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(back)
                .addGap(140, 140, 140)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back)))
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TopBooks)
                    .addComponent(TopCustomers)
                    .addComponent(TotalSales))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TopBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TopBooksActionPerformed
        // TODO add your handling code here:
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        Connection con = connection.getConnection();
        String query = "{call topBooks()}";
        PreparedStatement p ;
        ResultSet rs;
        try {
            p = con.prepareStatement(query);
            rs = p.executeQuery();
            TopBooks form = new TopBooks();
            while (rs.next()){
                String Title_Result = rs.getString("Title");
                String Sales_copies_Result = String.valueOf(rs.getInt("Sales_copies"));
                String BOOK_ISBN_Result = String.valueOf(rs.getInt("BOOK_ISBN"));
                String tdData[]={BOOK_ISBN_Result,Title_Result,Sales_copies_Result};
                DefaultTableModel tblModel = (DefaultTableModel)form.Table.getModel();
                tblModel.addRow(tdData);
            }
            for(int i=0; i<3; i++){
                form.Table.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
            }
            form.setVisible(true);
            form.pack();
            form.setLocationRelativeTo(null);
            form.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.setVisible(false);
        }
          
         catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
    }//GEN-LAST:event_TopBooksActionPerformed

    private void TotalSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalSalesActionPerformed
        // TODO add your handling code here:
        //open manager form
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        Connection con = connection.getConnection();
        String query = "{call sales_for_month()}";
        PreparedStatement p ;
        ResultSet rs;
        try {
            p = con.prepareStatement(query);
            rs = p.executeQuery();
            TotalSales form = new TotalSales();
            while (rs.next()){
                String Title_Result = rs.getString("Title");
                String Price_Result = String.valueOf(rs.getInt("Price"));
                String BOOK_ISBN_Result = String.valueOf(rs.getInt("BOOK_ISBN"));
                String Copies_Result = String.valueOf(rs.getInt("Copies"));
                String tdData[]={BOOK_ISBN_Result,Title_Result,Price_Result,Copies_Result};
                DefaultTableModel tblModel = (DefaultTableModel)form.Table.getModel();
                tblModel.addRow(tdData);
            }
            for(int i=0; i<4; i++){
                form.Table.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
            }
            form.setVisible(true);
            form.pack();
            form.setLocationRelativeTo(null);
            form.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.setVisible(false);
        }
          
         catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
    }//GEN-LAST:event_TotalSalesActionPerformed

    private void TopCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TopCustomersActionPerformed
        // TODO add your handling code here:
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        Connection con = connection.getConnection();
        String query = "{call topCustomers()}";
        PreparedStatement p ;
        ResultSet rs;
        try {
            p = con.prepareStatement(query);
            rs = p.executeQuery();
            TopCustomers form = new TopCustomers();
            while (rs.next()){
                String First_Name_Result = rs.getString("FIRST_NAME");
                String Last_Name_Result = rs.getString("LAST_NAME");
                String Price_Result = String.valueOf(rs.getInt("total_price"));
                String tdData[]={First_Name_Result,Last_Name_Result,Price_Result};
                DefaultTableModel tblModel = (DefaultTableModel)form.Table.getModel();
                tblModel.addRow(tdData);
            }
            for(int i=0; i<3; i++){
                form.Table.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
            }
            form.setVisible(true);
            form.pack();
            form.setLocationRelativeTo(null);
            form.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.setVisible(false);
        }
          
         catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
     
    }//GEN-LAST:event_TopCustomersActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed

        ManagerMode form = new ManagerMode();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        form.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TopBooks;
    private javax.swing.JButton TopCustomers;
    private javax.swing.JButton TotalSales;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
